import { AmalCategory, AmalTarget, AmalType } from "./types";

export const RAMADAN_START_DATE = "2026-03-20"; // Approximate for 1447H
export const RAMADAN_DAYS = 30;

export const AMAL_TARGETS: AmalTarget[] = [
  // INDIVIDU
  {
    id: "puasa",
    label: "Menjaga Puasa (Lisan, Hati, Perilaku)",
    category: AmalCategory.INDIVIDU,
    type: AmalType.BOOLEAN,
    targetValue: 1,
    frequency: "daily",
  },
  {
    id: "tilawah",
    label: "Tilawah Al-Quran (Target 2x Khatam)",
    category: AmalCategory.INDIVIDU,
    type: AmalType.NUMBER,
    targetValue: 2,
    unit: "Juz",
    description: "Target harian untuk 2x khatam adalah 2 Juz per hari",
    frequency: "daily",
  },
  {
    id: "al-mulk",
    label: "Hafal & Tadabbur Al-Mulk",
    category: AmalCategory.INDIVIDU,
    type: AmalType.BOOLEAN,
    targetValue: 1,
    frequency: "daily",
  },
  {
    id: "juz-30",
    label: "Murajaah/Hafal Juz 30",
    category: AmalCategory.INDIVIDU,
    type: AmalType.BOOLEAN,
    targetValue: 1,
    frequency: "daily",
  },
  {
    id: "tasbih",
    label: "Bertasbih (Min 300x)",
    category: AmalCategory.INDIVIDU,
    type: AmalType.NUMBER,
    targetValue: 300,
    unit: "x",
    frequency: "daily",
  },
  {
    id: "tarawih",
    label: "Shalat Tarawih & Witir",
    category: AmalCategory.INDIVIDU,
    type: AmalType.BOOLEAN,
    targetValue: 1,
    frequency: "daily",
  },
  {
    id: "berjamaah",
    label: "Shalat Berjamaah (Min 3x)",
    category: AmalCategory.INDIVIDU,
    type: AmalType.NUMBER,
    targetValue: 3,
    unit: "Waktu",
    frequency: "daily",
  },
  {
    id: "qiyaamul-lail",
    label: "Qiyaamul Lail (Min 2 Rakaat)",
    category: AmalCategory.INDIVIDU,
    type: AmalType.NUMBER,
    targetValue: 2,
    unit: "Rakaat",
    frequency: "daily",
  },
  {
    id: "dhuha",
    label: "Shalat Dhuha (Min 4 Rakaat)",
    category: AmalCategory.INDIVIDU,
    type: AmalType.NUMBER,
    targetValue: 4,
    unit: "Rakaat",
    frequency: "daily",
  },
  {
    id: "rawatib",
    label: "Shalat Rawatib (Min 10 Rakaat)",
    category: AmalCategory.INDIVIDU,
    type: AmalType.NUMBER,
    targetValue: 10,
    unit: "Rakaat",
    frequency: "daily",
  },
  {
    id: "istighfar",
    label: "Istighfar Sahur (100x)",
    category: AmalCategory.INDIVIDU,
    type: AmalType.NUMBER,
    targetValue: 100,
    unit: "x",
    frequency: "daily",
  },
  {
    id: "dzikir-pagi-sore",
    label: "Dzikir Pagi & Sore",
    category: AmalCategory.INDIVIDU,
    type: AmalType.BOOLEAN,
    targetValue: 1,
    frequency: "daily",
  },
  {
    id: "wirid-10-akhir",
    label: "Wirid Doa 10 Hari Terakhir",
    category: AmalCategory.INDIVIDU,
    type: AmalType.BOOLEAN,
    targetValue: 1,
    frequency: "last10days",
  },
  {
    id: "sedekah",
    label: "Sedekah Harian (Min Rp 2000)",
    category: AmalCategory.INDIVIDU,
    type: AmalType.CURRENCY,
    targetValue: 2000,
    unit: "Rupiah",
    frequency: "daily",
  },
  {
    id: "doa-khusus",
    label: "Doa Khusus Bangsa & Umat",
    category: AmalCategory.INDIVIDU,
    type: AmalType.BOOLEAN,
    targetValue: 1,
    frequency: "daily",
  },

  // KELUARGA & MASYARAKAT
  {
    id: "kumpul-keluarga",
    label: "Kumpul Keluarga (Min 1x Pekan)",
    category: AmalCategory.KELUARGA_MASYARAKAT,
    type: AmalType.BOOLEAN,
    targetValue: 1,
    frequency: "weekly",
  },
  {
    id: "tadabbur-keluarga",
    label: "Tilawah & Tadabbur Juz 30 Bersama",
    category: AmalCategory.KELUARGA_MASYARAKAT,
    type: AmalType.BOOLEAN,
    targetValue: 1,
    frequency: "daily",
  },
  {
    id: "sahur-bersama",
    label: "Sahur Bersama & Tadarusan",
    category: AmalCategory.KELUARGA_MASYARAKAT,
    type: AmalType.BOOLEAN,
    targetValue: 1,
    frequency: "daily",
  },
  {
    id: "subuh-masjid",
    label: "Subuh di Masjid Bersama Keluarga",
    category: AmalCategory.KELUARGA_MASYARAKAT,
    type: AmalType.BOOLEAN,
    targetValue: 1,
    frequency: "daily",
  },
  {
    id: "ifthor-keluarga",
    label: "Ifthor Bersama Keluarga (Min 3x Pekan)",
    category: AmalCategory.KELUARGA_MASYARAKAT,
    type: AmalType.BOOLEAN,
    targetValue: 1,
    frequency: "weekly",
  },
  {
    id: "tarawih-keluarga",
    label: "Tarawih Bersama Keluarga (Min 5x Pekan)",
    category: AmalCategory.KELUARGA_MASYARAKAT,
    type: AmalType.BOOLEAN,
    targetValue: 1,
    frequency: "weekly",
  },
  {
    id: "itikaf-keluarga",
    label: "Itikaf Bersama Keluarga (Min 3x 10 Hari Akhir)",
    category: AmalCategory.KELUARGA_MASYARAKAT,
    type: AmalType.BOOLEAN,
    targetValue: 1,
    frequency: "last10days",
  },
  {
    id: "memberi-ifthor",
    label: "Memberi Ifthor (Min 1x Pekan)",
    category: AmalCategory.KELUARGA_MASYARAKAT,
    type: AmalType.BOOLEAN,
    targetValue: 1,
    frequency: "weekly",
  },
  {
    id: "partisipasi-kegiatan",
    label: "Partisipasi Kegiatan Ramadhan (Min 1x Pekan)",
    category: AmalCategory.KELUARGA_MASYARAKAT,
    type: AmalType.BOOLEAN,
    targetValue: 1,
    frequency: "weekly",
  },
  {
    id: "sedekah-keluarga",
    label: "Sedekah Keluarga (Celengan)",
    category: AmalCategory.KELUARGA_MASYARAKAT,
    type: AmalType.BOOLEAN,
    targetValue: 1,
    frequency: "daily",
  },
];
